spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: '{cipher}74dd65389d40114c9e36be09b5a4cf8d017aa8dd6dc4a4c6564475ac6ebdf551'

token:
  expiration_time: 8640000
  secret: user_token_default

gateway:
  ip: 172.30.1.18

order_service:
  url: http://order-service/%s/orders
  exception:
  order_is_empty: User's order is empty