spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 123123

token:
  expiration_time: 86400000
  secret: user_token_default

gateway:
  ip: 172.30.1.18